### ISSUE TITLE
useClickOutside is not a function

### ISSUE THREAD

**Issue by AndyHryshchenko** [djkepa/custom-react-hooks#1]
Hi, tried using your hook while installing only it (not "/all"), tried using a named import:

`import { useClickOutside } from '@custom-react-hooks/use-click-outside';`

Got this error:

`sidebar.tsx:18 Uncaught TypeError: useClickOutside is not a function`

Clearly it's because the hook doesn't have a named export, but exports default. I was able to use changing to:

`import useClickOutside from '@custom-react-hooks/use-click-outside';`

But I would suggest either including named imports (they're just more convenient) to all of your hooks or supplementing the docs with this little nuance.

Thanks for the hook!

**Comment by djkepa** [comment]
Hi Andy,

Thank you so much for your feedback regarding the useClickOutside hook. I appreciate you taking the time to highlight the difficulties you encountered with the import process.

To follow up on your suggestion, I've streamlined the hook to support named imports exclusively, ensuring consistency and ease of use. This update should make the integration of the hook more straightforward.

Please update to the latest version to take advantage of these improvements:

```bash
npm update @custom-react-hooks/use-click-outside
```

I've also updated the documentation to reflect this change and provide clear guidance on how to import the hook. I hope this resolves the issues you experienced and enhances your development process. Please do let me know how it works out for you, or if there's anything else I can improve. Your input is incredibly valuable!

Best regards,
Bane
